language: python

python:
  - "3.7"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment

  - conda -c conda-forge pyfmi
  - pip install -r requirements.txt
  - pip install .[all]
  - pip install -r requirements_dev.txt

script:
  - pytest
  - cd docs
  - make html
  - touch _build/html/.nojekyll
  - bash <(curl -s https://codecov.io/bash)  # code coverage report upload
  - cd ..

deploy:
  - provider: pages
    strategy: git
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # shared with travis-ci.org dashboard
    keep_history: true
    on:
      branch: master
    local_dir: docs/_build/html/

  - provider: pypi
    user: "__token__"
    password: $PYPI_TOKEN
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true