language: python

python:
  - "3.7" # Travis Python is actually not used since we use conda, but this keeps it organized.

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a  # Useful for debugging any issues with conda

  - conda create -q -n venv  -c conda-forge python=$TRAVIS_PYTHON_VERSION pyfmi
  - conda activate venv

  - pip install -r requirements.txt
  - pip install .[all]
  - pip install -r requirements_dev.txt

script:
  - pytest
  - cd docs
  - make html
  - touch _build/html/.nojekyll
  - bash <(curl -s https://codecov.io/bash)  # code coverage report upload
  - cd $TRAVIS_BUILD_DIR

deploy:
  - provider: pages
    strategy: git
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # shared with travis-ci.org dashboard
    keep_history: true
    on:
      branch: master
    local_dir: docs/_build/html/

  - provider: pypi
    user: "__token__"
    password: $PYPI_TOKEN
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true